apiVersion: v1
kind: Namespace

metadata:
  name: dev-indri
  labels:
    project: indri
    env: dev
    owner: nd
    team: platform
    costcenter: dev-indri
    object: namespace
    tag: namespace-dev-indri
