apiVersion: v1
kind: Service

metadata:
  name: svc-app-ingest
  namespace: dev-indri
  labels:
    project: indri
    app: app-ingest
    env: dev
    owner: nd
    team: platform
    costcenter: dev-indri
    object: service
    tag: svc-app-ingest

spec:
  type: ClusterIP
  selector:
    pod: pod-app-ingest
  ports:
  - name: port-ingest
    port: 8000
    targetPort: 8000