apiVersion: v1
kind: Service

metadata:
  name: svc-app-backend
  namespace: dev-indri
  labels:
    project: indri
    app: app-backend
    env: dev
    owner: nd
    team: platform
    costcenter: dev-indri
    object: service
    tag: svc-app-backend

spec:
  type: ClusterIP
  selector:
    pod: pod-app-backend
  ports:
  - name: port-backend
    port: 8000
    targetPort: 8000